language: go

go:
 - 1.11.x
 - 1.12.x
 - 1.13.x

os:
  - linux

dist: bionic

env:
  - GO111MODULE=on

before_script:
  - sudo apt-get update
  - sudo apt-get install -y libc6:i386 libstdc++6:i386
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -v -race --coverprofile=c.out ./...
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - make

after_script:
  - make clean
  - go test -v -run=NONE -bench . -benchmem ./...
